name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Go 1.25.6
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 1.25.6
      
      - name: Get the version
        id: tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Login docker
        run: docker login https://ghcr.io -u wquintal -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Docker build
        run: docker build -t ghcr.io/bascanada/logviewer:${VERSION} .
        env:
          VERSION: ${{ steps.tag.outputs.tag }}
      
      - name: Docker push
        run: docker push ghcr.io/bascanada/logviewer:${VERSION}
        env:
          VERSION: ${{ steps.tag.outputs.tag }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c9ea19e37eb465b83766dbbf597b29dc5020bdf # v6.2.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
