name: Trigger Public Site Rebuild

on:
  push:
    branches:
      - main
    paths:
      # Ne d√©clencher que si ces fichiers changent
      - 'README.md'
      - '*.gif'

permissions: read-all

jobs:
  notify-public-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Dispatch Event to Public Repo
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: bascanada/public
          event-type: update-docs
          client-payload: '{"source_commit": "${{ github.sha }}", "message": "Update triggered by logviewer README/GIF change"}'