name: Trigger Public Site Rebuild

on:
  push:
    branches:
      - main
    paths:
      # Ne d√©clencher que si ces fichiers changent
      - 'README.md'
      - '*.gif'

permissions:
  contents: read

jobs:
  notify-public-site:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to Public Repo
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: bascanada/public
          event-type: update-docs
          client-payload: '{"source_commit": "${{ github.sha }}", "message": "Update triggered by logviewer README/GIF change"}'